In [22]:
from tensorflow.keras.preprocessing.text import one_hot


In [23]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [24]:
voc_size=10000


In [25]:
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr 

[[5862, 2105, 8373, 9799],
 [5862, 2105, 8373, 6296],
 [5862, 1882, 8373, 9114],
 [2949, 6128, 9259, 967, 2400],
 [2949, 6128, 9259, 967, 3351],
 [7055, 5862, 3781, 8373, 1466],
 [7609, 2673, 4453, 967]]

In [26]:
from tensorflow.keras.layers import Embedding 
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [27]:
import numpy as np


In [28]:
sent_length= 8
embedded_docs=pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5862 2105 8373 9799]
 [   0    0    0    0 5862 2105 8373 6296]
 [   0    0    0    0 5862 1882 8373 9114]
 [   0    0    0 2949 6128 9259  967 2400]
 [   0    0    0 2949 6128 9259  967 3351]
 [   0    0    0 7055 5862 3781 8373 1466]
 [   0    0    0    0 7609 2673 4453  967]]


In [29]:
dim=10
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')


In [30]:
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 5862, 2105, 8373, 9799])

In [32]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 64ms/step


array([[-1.2335815e-02, -2.3533309e-02, -2.7630663e-02, -2.5536681e-02,
         7.6579824e-03, -3.8877353e-03, -1.5147410e-02,  1.2803007e-02,
         2.7302075e-02, -4.1929435e-02],
       [-1.2335815e-02, -2.3533309e-02, -2.7630663e-02, -2.5536681e-02,
         7.6579824e-03, -3.8877353e-03, -1.5147410e-02,  1.2803007e-02,
         2.7302075e-02, -4.1929435e-02],
       [-1.2335815e-02, -2.3533309e-02, -2.7630663e-02, -2.5536681e-02,
         7.6579824e-03, -3.8877353e-03, -1.5147410e-02,  1.2803007e-02,
         2.7302075e-02, -4.1929435e-02],
       [-1.2335815e-02, -2.3533309e-02, -2.7630663e-02, -2.5536681e-02,
         7.6579824e-03, -3.8877353e-03, -1.5147410e-02,  1.2803007e-02,
         2.7302075e-02, -4.1929435e-02],
       [ 1.8872730e-03,  3.4769129e-02,  6.7943446e-03, -1.7377030e-02,
         4.0757656e-03,  3.2741200e-02, -4.0681362e-03, -4.8591554e-02,
        -2.7859498e-02,  1.8342409e-02],
       [-2.4316585e-02,  1.5989471e-02, -7.6023117e-03,  4.6290457e-05,
   

: 

: 

: 

: 

: 

: 